### ISSUE TITLE
git+https://github.com/xx025/requests_enhance.git失效无法安装

### ISSUE THREAD

**Issue by qiujunhan** [xx025/yzw-dl#4]
似乎这个链接失效了，我用pip安装这个包都不行，请问怎么修复

**Comment by xx025** [comment]
这是我很久之前写的一个程序，当时实现方式比较粗糙，（如果不是很有价值我都隐藏了），requests_enhance 主要在做请求失败重试的事情

现在我已经重新打开了  requests_enhance 仓库，可以继续测试使用，尽量不要再依赖他

**Comment by qiujunhan** [comment]
> 这是我很久之前写的一个程序，当时实现方式比较粗糙，（如果不是很有价值我都隐藏了），requests_enhance 主要在做请求失败重试的事情
> 
> 现在我已经重新打开了 [requests_enhance](https://github.com/xx025/requests-enhance) 仓库，可以继续测试使用，尽量不要再依赖他

非常感谢，我自己实现的跑不通，点赞关注了
